import { useTheme } from 'next-themes'
import React from 'react'

export function AppFooter() {
  const { theme } = useTheme()
  return (
    <footer
      className={`text-center p-2 text-xs ${theme === 'dark' ? 'bg-neutral-900 text-neutral-400' : 'bg-neutral-100'}`}
    >
      Generated by{' '}
      <a
        className="link hover:text-neutral-500 dark:hover:text-white"
        href="https://github.com/solana-developers/create-solana-dapp"
        target="_blank"
        rel="noopener noreferrer"
      >
        create-solana-dapp
      </a>
    </footer>
  )
}
