[toolchain]
package_manager = "pnpm"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
grpx_dprotocols = "GHMkgYRXD5zosBjEePwZ3fdxTwdMF5XhCZhFqVQcM9sQ"

[programs.devnet]
grpx_dprotocols = "GHMkgYRXD5zosBjEePwZ3fdxTwdMF5XhCZhFqVQcM9sQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"